# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jared Gray
description: "Software developer living in Gilbert, AZ. Available for contract for software projects or website design and building."
keywords: "Software, Engineer, Gilbert, Phoenix, Web Development, Jared Gray"
url: https://www.jared-gray.com

google_analytics: UA-60775504-1
repo: http://github.com/jd-gray/jared_blog

# Author settings
author:
  name: Jared Gray
  bio: "Software Engineer"
  thumb: /images/author.jpg
  email: jared@jaredgray.us
  url: https://jared-gray.com
  github: https://github.com/jd-gray
  linkedin: https://www.linkedin.com/in/jareddgray/

# navbar pages
navbar:
  - slug: blog
    title: Blog

includes:
  - blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md"]
