title: Jared Gray
email: jared@jaredgray.us
description: >-
  Software Developer + Triathlete
url: "https://www.jared-gray.com"
github_username:  jd-gray
markdown: kramdown
theme: minima
google_analytics:
